name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:   
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: LapoElisacci/metrics@master
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LapoElisacci
          template: classic
          base: header, activity, community
          config_timezone: Europe/Rome

  notable:
    runs-on: ubuntu-latest
    steps:
      - uses: LapoElisacci/metrics@master
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LapoElisacci
          template: classic
          base: ""
          config_display: large
          config_timezone: Europe/Rome
          config_output: svg
          filename: notable.svg

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>75

  language:
    runs-on: ubuntu-latest
    steps:
      - uses: LapoElisacci/metrics@master
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LapoElisacci
          template: classic
          base: ""
          config_display: large
          config_timezone: Europe/Rome
          config_output: svg
          filename: language.svg

          # Language plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: vue, php, css

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: LapoElisacci/metrics@master
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LapoElisacci
          template: classic
          base: ""
          config_display: large
          config_timezone: Europe/Rome
          config_output: svg
          filename: achievements.svg

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact 
